# permissions for end users to view githooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: githook-viewer-role
rules:
- apiGroups:
  - tools.my.domain
  resources:
  - githooks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tools.my.domain
  resources:
  - githooks/status
  verbs:
  - get
